### ISSUE TITLE
ciで`println!``dbg`がある場合は落ちるようにする

### ISSUE THREAD

**Issue by bokutotu** [bokutotu/zenu#4]

**Comment by senkenn** [comment]
> @senkenn
> 
> * `Cargo.toml`と同じディレクトリにある、`build.rs`は検索対象から外してほしい。
> * `examples`ディレクトリも外してほしい。

今clippyは`zenu-matrix`のみのため、examples, build.rsはそもそも含まれていない

**Comment by bokutotu** [comment]
含めて見てほしいです🙇‍♂️

**Comment by senkenn** [comment]
おけ、ビルドできるディレクトリでclippyできるようにしてみるわ

**Comment by bokutotu** [comment]
それはclippyの機能じゃない気がする

**Comment by senkenn** [comment]
clippy入れたときにrootだとそもそもcargo buildができないから、buildできるzenu-matrixだけclippyチェックしとこうか〜って経緯だったよ

**Comment by bokutotu** [comment]
そうだったわ

**Comment by senkenn** [comment]
> おけ、ビルドできるディレクトリでclippyできるようにしてみるわ

こうする？

**Comment by senkenn** [comment]
今ビルドできるの zenu-matrix と zenu-matrix-test だけだわ
